services:
  - type: web
    name: lawfirm-manager-pro
    env: node
    buildCommand: "npm install"
    startCommand: "npm start"
    plan: free
    autoDeploy: true
    envVars:
      - key: NODE_VERSION
        value: 18
      - key: SESSION_SECRET
        generateValue: true
